### ISSUE TITLE
merge() in concatenate_layers() is being called with mode='sum' when using Keras 1

### ISSUE THREAD

**Issue by aitorshuffle** [costapt/vess2ret#4]
Hi,

Since the addition of the compatibility with Keras 2, [the call to merge() in concatenate_layers()](https://github.com/costapt/vess2ret/blob/master/models.py#L34) no longer includes the `mode` parameter when used with Keras 1. Thus, merge() is now called with the default `mode='sum'` default value instead of with 'concat', which I understand that is not the expected behaviour (and crashes if the number of channels is different for A and B).

Many thanks for sharing this work!

Best,

Aitor

**Comment by costapt** [comment]
Hi, 

Thank you for pointing out the error. 
The merge layer is now using the mode parameter and so I think this issue is solved now.

Thanks again.
